goog.provide('manager.views.schemas.enums');
manager.views.schemas.enums.value_form = (function manager$views$schemas$enums$value_form(path){
return cljs.core.with_meta(new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.subform,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.text_input,new cljs.core.Keyword(null,"enum-value","enum-value",-1046516274),"Value:",path], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.text_input,new cljs.core.Keyword(null,"description","description",-1428560544),"Description:",path], null),new cljs.core.PersistentVector(null, 6, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.text_input_with_toggle,new cljs.core.Keyword(null,"deprecated","deprecated",1498275348),"Deprecated:",new cljs.core.Keyword(null,"isDeprecated","isDeprecated",1354226910),path,cljs.core.with_meta(new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"span.input-group-btn","span.input-group-btn",358441272),new cljs.core.PersistentVector(null, 6, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.button,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"style","style",-496642736),new cljs.core.Keyword(null,"warning","warning",-1685650671),new cljs.core.Keyword(null,"label","label",1718410804),"Delete"], null),new cljs.core.Keyword(null,"delete-resource-property","delete-resource-property",1595588749),cljs.core.butlast(path),cljs.core.last(path),true], null)], null),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"key","key",-1516042587),new cljs.core.Keyword(null,"delete","delete",-1768633620)], null))], null)], null),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"key","key",-1516042587),cljs.core.last(path)], null));
});
manager.views.schemas.core.form.cljs$core$IMultiFn$_add_method$arity$3(null,new cljs.core.Keyword(null,"enums","enums",-1800115173),(function (){
var base_path = new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"data","data",-232669377),new cljs.core.Keyword(null,"values","values",372645556)], null);
var values = cljs.core.get_in.cljs$core$IFn$_invoke$arity$3(cljs.core.deref(re_frame.core.subscribe.cljs$core$IFn$_invoke$arity$1(new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"get-resource","get-resource",-2146213108)], null))),base_path,cljs.core.PersistentArrayMap.EMPTY);
return new cljs.core.PersistentVector(null, 6, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.scaffold,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.header], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.inputs,null,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.name_input,"Enum"], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.text_input,new cljs.core.Keyword(null,"description","description",-1428560544),"Description:",manager.components.form.root], null)], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.row,new cljs.core.Keyword(null,"middle","middle",-701029031),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"h4","h4",2004862993),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"span.page-header","span.page-header",184350353),"Values:"], null)], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.button,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"style","style",-496642736),new cljs.core.Keyword(null,"info","info",-317069002),new cljs.core.Keyword(null,"label","label",1718410804),"Add"], null),new cljs.core.Keyword(null,"new-resource-property","new-resource-property",1251627722),new cljs.core.Keyword(null,"values","values",372645556),true], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.subform_list,new cljs.core.Keyword(null,"lg","lg",-80787836),cljs.core.map_indexed.cljs$core$IFn$_invoke$arity$2((function (idx,_){
return manager.views.schemas.enums.value_form(cljs.core.conj.cljs$core$IFn$_invoke$arity$2(base_path,idx));
}),cljs.core.sort_by.cljs$core$IFn$_invoke$arity$2(new cljs.core.Keyword(null,"enum-value","enum-value",-1046516274),values))], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.footer], null)], null);
}));

//# sourceMappingURL=manager.views.schemas.enums.js.map
