goog.provide('manager.schemas');
manager.schemas.non_blank = (function manager$schemas$non_blank(value){
return schema.core.conditional.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.comp.cljs$core$IFn$_invoke$arity$2(cljs.core.not,clojure.string.blank_QMARK_),value], 0));
});
manager.schemas.non_empty = (function manager$schemas$non_empty(value){
return schema.core.conditional.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([cljs.core.not_empty,value], 0));
});
manager.schemas.valid_type = (function manager$schemas$valid_type(value){
return schema.core.conditional.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (p1__25713_SHARP_){
return cljs.core.not_empty(cljs.core.disj.cljs$core$IFn$_invoke$arity$variadic(p1__25713_SHARP_,"non-null",cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["list"], 0)));
}),value], 0));
});
manager.schemas.new_resource = (function manager$schemas$new_resource(data){
return cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.required_key(new cljs.core.Keyword(null,"path","path",-188191168)),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [schema.core.Keyword], null),schema.core.required_key(new cljs.core.Keyword(null,"old-name","old-name",1289683869)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"name","name",1843675177)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"data","data",-232669377)),data]);
});
/**
 * 
 */
manager.schemas.Object = cljs.core.vary_meta.cljs$core$IFn$_invoke$arity$4(schema.core.schema_with_name(manager.schemas.new_resource(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.optional_key(new cljs.core.Keyword(null,"implements","implements",1804973047)),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [schema.core.Str], null),schema.core.required_key(new cljs.core.Keyword(null,"fields","fields",-1932066230)),manager.schemas.non_empty(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.Keyword,cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"type","type",1174270348)),manager.schemas.valid_type(cljs.core.PersistentHashSet.createAsIfByAssoc([schema.core.Str])),schema.core.optional_key(new cljs.core.Keyword(null,"isDeprecated","isDeprecated",1354226910)),schema.core.Bool,schema.core.optional_key(new cljs.core.Keyword(null,"deprecated","deprecated",1498275348)),schema.core.Str])]))])),new cljs.core.Symbol(null,"Object","Object",61210754,null)),cljs.core.assoc,new cljs.core.Keyword(null,"ns","ns",441598760),new cljs.core.Symbol(null,"manager.schemas","manager.schemas",-2045580359,null));
/**
 * 
 */
manager.schemas.InputObject = cljs.core.vary_meta.cljs$core$IFn$_invoke$arity$4(schema.core.schema_with_name(manager.schemas.new_resource(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"fields","fields",-1932066230)),manager.schemas.non_empty(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.Keyword,cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"type","type",1174270348)),manager.schemas.valid_type(cljs.core.PersistentHashSet.createAsIfByAssoc([schema.core.Str])),schema.core.optional_key(new cljs.core.Keyword(null,"default-value","default-value",232220170)),schema.core.Bool,schema.core.optional_key(new cljs.core.Keyword(null,"isDeprecated","isDeprecated",1354226910)),schema.core.Bool,schema.core.optional_key(new cljs.core.Keyword(null,"deprecated","deprecated",1498275348)),schema.core.Str])]))])),new cljs.core.Symbol(null,"InputObject","InputObject",1723067961,null)),cljs.core.assoc,new cljs.core.Keyword(null,"ns","ns",441598760),new cljs.core.Symbol(null,"manager.schemas","manager.schemas",-2045580359,null));
/**
 * 
 */
manager.schemas.Interface = cljs.core.vary_meta.cljs$core$IFn$_invoke$arity$4(schema.core.schema_with_name(manager.schemas.new_resource(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"fields","fields",-1932066230)),manager.schemas.non_empty(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.Keyword,cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"type","type",1174270348)),manager.schemas.valid_type(cljs.core.PersistentHashSet.createAsIfByAssoc([schema.core.Str]))])]))])),new cljs.core.Symbol(null,"Interface","Interface",-1654332275,null)),cljs.core.assoc,new cljs.core.Keyword(null,"ns","ns",441598760),new cljs.core.Symbol(null,"manager.schemas","manager.schemas",-2045580359,null));
/**
 * 
 */
manager.schemas.Union = cljs.core.vary_meta.cljs$core$IFn$_invoke$arity$4(schema.core.schema_with_name(manager.schemas.new_resource(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.optional_key(new cljs.core.Keyword(null,"members","members",159001018)),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [schema.core.Str], null)])),new cljs.core.Symbol(null,"Union","Union",424739804,null)),cljs.core.assoc,new cljs.core.Keyword(null,"ns","ns",441598760),new cljs.core.Symbol(null,"manager.schemas","manager.schemas",-2045580359,null));
/**
 * 
 */
manager.schemas.Enum = cljs.core.vary_meta.cljs$core$IFn$_invoke$arity$4(schema.core.schema_with_name(manager.schemas.new_resource(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"values","values",372645556)),manager.schemas.non_empty(new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"enum-value","enum-value",-1046516274)),manager.schemas.non_blank(schema.core.Str),schema.core.optional_key(new cljs.core.Keyword(null,"isDeprecated","isDeprecated",1354226910)),schema.core.Bool,schema.core.optional_key(new cljs.core.Keyword(null,"deprecated","deprecated",1498275348)),schema.core.Str])], null))])),new cljs.core.Symbol(null,"Enum","Enum",505307200,null)),cljs.core.assoc,new cljs.core.Keyword(null,"ns","ns",441598760),new cljs.core.Symbol(null,"manager.schemas","manager.schemas",-2045580359,null));
/**
 * 
 */
manager.schemas.Query = cljs.core.vary_meta.cljs$core$IFn$_invoke$arity$4(schema.core.schema_with_name(manager.schemas.new_resource(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"source","source",-433931539)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"args","args",1315556576)),manager.schemas.non_empty(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.Keyword,cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"type","type",1174270348)),manager.schemas.valid_type(cljs.core.PersistentHashSet.createAsIfByAssoc([schema.core.Str]))])]))])),new cljs.core.Symbol(null,"Query","Query",-1294114,null)),cljs.core.assoc,new cljs.core.Keyword(null,"ns","ns",441598760),new cljs.core.Symbol(null,"manager.schemas","manager.schemas",-2045580359,null));
/**
 * 
 */
manager.schemas.Mutation = cljs.core.vary_meta.cljs$core$IFn$_invoke$arity$4(schema.core.schema_with_name(manager.schemas.new_resource(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"source","source",-433931539)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"args","args",1315556576)),manager.schemas.non_empty(cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.Keyword,cljs.core.PersistentArrayMap.createAsIfByAssoc([schema.core.optional_key(new cljs.core.Keyword(null,"description","description",-1428560544)),schema.core.Str,schema.core.required_key(new cljs.core.Keyword(null,"type","type",1174270348)),manager.schemas.valid_type(cljs.core.PersistentHashSet.createAsIfByAssoc([schema.core.Str]))])]))])),new cljs.core.Symbol(null,"Mutation","Mutation",2042651179,null)),cljs.core.assoc,new cljs.core.Keyword(null,"ns","ns",441598760),new cljs.core.Symbol(null,"manager.schemas","manager.schemas",-2045580359,null));

//# sourceMappingURL=manager.schemas.js.map
