goog.provide('manager.views.schemas');
manager.views.schemas.schemas_form.cljs$core$IMultiFn$_add_method$arity$3(null,new cljs.core.Keyword(null,"inputs","inputs",865803858),(function (){
return new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.scaffold,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.row,new cljs.core.Keyword(null,"top","top",-1856271961),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"button.btn.btn-success","button.btn.btn-success",574341715),"Create New"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"button.btn.btn-danger","button.btn.btn-danger",533883282),"Delete"], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.name_input,"Input"], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.text_input,new cljs.core.Keyword(null,"description","description",-1428560544),"Description:",manager.components.form.root], null)], null);
}));
manager.views.schemas.schemas_form.cljs$core$IMultiFn$_add_method$arity$3(null,new cljs.core.Keyword(null,"interfaces","interfaces",-171349120),(function (){
return new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.scaffold,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.row,new cljs.core.Keyword(null,"top","top",-1856271961),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"button.btn.btn-success","button.btn.btn-success",574341715),"Create New"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"button.btn.btn-danger","button.btn.btn-danger",533883282),"Delete"], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.name_input,"Interface"], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.text_input,new cljs.core.Keyword(null,"description","description",-1428560544),"Description:",manager.components.form.root], null)], null);
}));
manager.views.schemas.schemas_form.cljs$core$IMultiFn$_add_method$arity$3(null,new cljs.core.Keyword(null,"unions","unions",347029800),(function (){
return new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.scaffold,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.row,new cljs.core.Keyword(null,"top","top",-1856271961),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"button.btn.btn-success","button.btn.btn-success",574341715),"Create New"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"button.btn.btn-danger","button.btn.btn-danger",533883282),"Delete"], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.name_input,"Union"], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.text_input,new cljs.core.Keyword(null,"description","description",-1428560544),"Description:",manager.components.form.root], null),new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.multi_select_input,new cljs.core.Keyword(null,"members","members",159001018),"Members:",new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"types","types",590030639)], null),manager.components.form.root], null)], null);
}));
manager.views.schemas.schemas_form.cljs$core$IMultiFn$_add_method$arity$3(null,new cljs.core.Keyword(null,"enums","enums",-1800115173),(function (){
return new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.scaffold,new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.row,new cljs.core.Keyword(null,"top","top",-1856271961),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"button.btn.btn-success","button.btn.btn-success",574341715),"Create New"], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"button.btn.btn-danger","button.btn.btn-danger",533883282),"Delete"], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.name_input,"Enum"], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [manager.components.form.text_input,new cljs.core.Keyword(null,"description","description",-1428560544),"Description:"], null),manager.components.form.root], null);
}));

//# sourceMappingURL=manager.views.schemas.js.map
