name: API

on:
  pull_request:
    branches: [ master ]
    paths:
      - Codigo/**/*
      - .github/workflows/api.yaml

jobs:
  tests:
    defaults:
      run:
        working-directory: Codigo/bff-squared
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          lein: 2.9.1
        
      - name: Run tests
        run: lein test