name: Manager

on:
  pull_request:
    branches: [ master ]
    paths:
      - Codigo/*

jobs:
  tests:
    defaults:
      run:
        working-directory: Codigo/bff-squared
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test